// <auto-generated />
using System;
using ContactListRyberg.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactListRyberg.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210619032628_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactListRyberg.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Email = "ashewerw@sefse.com",
                            FirstName = "Alex",
                            LastName = "Ryberg",
                            PhoneNumber = 5555555555L
                        },
                        new
                        {
                            ContactId = 2,
                            Email = "alex@asdae.com",
                            FirstName = "Ashley",
                            LastName = "Green",
                            PhoneNumber = 9999999999L
                        },
                        new
                        {
                            ContactId = 3,
                            Email = "olive@green.com",
                            FirstName = "Olive",
                            LastName = "Green",
                            PhoneNumber = 3333333333L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
